<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxVfLPg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxVfLPg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNxVfLPg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNxVfLPg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNxVfLPg\App_KernelDevDebugContainer([
    'container.build_hash' => 'NxVfLPg',
    'container.build_id' => 'eaf5d413',
    'container.build_time' => 1589929310,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxVfLPg');
